name: intl_utils_formatter
description:
  "A utility package for intl_utils to sort and format the arb files."
version: 1.0.1
homepage: https://dholasain.com

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
